import os

DATABASE_URL = os.getenv("DATABASE_URL")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
BLOCK_LIMIT = int(os.getenv("BLOCK_LIMIT", 3))
BLOCK_DURATION_MINUTES = int(os.getenv("BLOCK_DURATION_MINUTES", 60))
